version: "3"
services:
     mosquitto:
        container_name: mosquitto
        restart: always
        build:
            context: ./build/mosquitto
            dockerfile: Dockerfile
        volumes:
            - ./etc/mosquitto:/mosquitto/config
            - ./var/data/mosquitto:/mosquitto/data
            - ./var/log/mosquitto:/mosquitto/log
        ports:
            - 1883:1883
#            - 8883:8883
#            - 9001:9001
#            - 9002:9002
        networks:
            - mosquitto-network

networks:
    mosquitto-network:
        driver: bridge
